title: Echo Chanel: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://echochan.github.io/echochanurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: echochan
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: crecho@live.cn